"""Data contracts for context-aware, AI-generated completions."""

from dataclasses import dataclass
from typing import Tuple


@dataclass(frozen=True)
class GeneratedSuggestion:
    """A completion generated by a model, never a corpus match."""

    text: str
    model: str


@dataclass(frozen=True)
class ContextualResult:
    """Generated suggestions and observable request latency."""

    suggestions: Tuple[GeneratedSuggestion, ...]
    model: str
    latency_ms: int
