# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: autocomplete.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'autocomplete.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x61utocomplete.proto\x12\x0f\x61utocomplete.v1\"o\n\rSearchRequest\x12\r\n\x05query\x18\x01 \x01(\t\x12)\n\x04mode\x18\x02 \x01(\x0e\x32\x1b.autocomplete.v1.SearchMode\x12\x0f\n\x07\x63ontext\x18\x03 \x01(\t\x12\x13\n\x0bmax_results\x18\x04 \x01(\r\"B\n\x0c\x43orpusOrigin\x12\x13\n\x0bsource_text\x18\x01 \x01(\t\x12\x0e\n\x06offset\x18\x02 \x01(\x04\x12\r\n\x05score\x18\x03 \x01(\x05\"\x19\n\x08\x41iOrigin\x12\r\n\x05model\x18\x01 \x01(\t\"~\n\nSuggestion\x12\x0c\n\x04text\x18\x01 \x01(\t\x12/\n\x06\x63orpus\x18\x02 \x01(\x0b\x32\x1d.autocomplete.v1.CorpusOriginH\x00\x12\'\n\x02\x61i\x18\x03 \x01(\x0b\x32\x19.autocomplete.v1.AiOriginH\x00\x42\x08\n\x06origin\"\x96\x01\n\x0eSearchResponse\x12/\n\x07request\x18\x01 \x01(\x0b\x32\x1e.autocomplete.v1.SearchRequest\x12\x30\n\x0bsuggestions\x18\x02 \x03(\x0b\x32\x1b.autocomplete.v1.Suggestion\x12\x12\n\nlatency_ms\x18\x03 \x01(\x04\x12\r\n\x05\x65rror\x18\x04 \x01(\t*U\n\nSearchMode\x12\x1b\n\x17SEARCH_MODE_UNSPECIFIED\x10\x00\x12\x16\n\x12SEARCH_MODE_CORPUS\x10\x01\x12\x12\n\x0eSEARCH_MODE_AI\x10\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'autocomplete_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SEARCHMODE']._serialized_start=528
  _globals['_SEARCHMODE']._serialized_end=613
  _globals['_SEARCHREQUEST']._serialized_start=39
  _globals['_SEARCHREQUEST']._serialized_end=150
  _globals['_CORPUSORIGIN']._serialized_start=152
  _globals['_CORPUSORIGIN']._serialized_end=218
  _globals['_AIORIGIN']._serialized_start=220
  _globals['_AIORIGIN']._serialized_end=245
  _globals['_SUGGESTION']._serialized_start=247
  _globals['_SUGGESTION']._serialized_end=373
  _globals['_SEARCHRESPONSE']._serialized_start=376
  _globals['_SEARCHRESPONSE']._serialized_end=526
# @@protoc_insertion_point(module_scope)
